name: Waka Readme Stats Updater

on:
  schedule:
    # Запускается каждые 3 часа или как вам удобно
    - cron: '0 */3 * * *'
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # --- Основные параметры для отображения ---
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_TIMEZONE: "true"
          SHOW_LANGUAGE: "true"
          SHOW_EDITORS: "true"
          SHOW_OS: "true"

          # --- Отключаем для минимализма (исходя из вашего запроса и скриншота) ---
          SHOW_LINES_OF_CODE: "false"     # Количество строк кода; для WakaTime это может быть не так важно, как общее время
                        # Операционные системы
          SHOW_PROJECTS: "false"          # Проекты (если не хотите их детализировать здесь)
                    # Редакторы кода
                    # Часовой пояс (обычно не нужен публично)
          SHOW_COMMIT: "false"          # Этот параметр про коммиты, а не специфику WakaTime
          SHOW_LANGUAGE_PER_REPO: "false" # Языки по репозиториям (может быть очень многословно)
          SHOW_LOC_CHART: "false"         # Вы упоминали, что "белый таймлайн" (график LOC) не нравится
          SHOW_DAYS_OF_WEEK: "false"      # Статистика по дням недели (чтобы не перегружать)
          SHOW_PROFILE_VIEWS: "false"     # Просмотры профиля (не относится к WakaTime)
          SHOW_SHORT_INFO: "false"        # Дополнительная краткая информация (убираем для фокуса)

          # --- Технические параметры ---
          LOCALE: "en"                    # Установите "ru" для русского или "en" для английского
          COMMIT_MESSAGE: "📊 Updated WakaTime coding stats" # Сообщение для коммита, который обновит README
          # SECTION_NAME: "waka"          # По умолчанию "waka", менять не нужно, если у вас ```
