name: Waka Readme Stats Updater

on:
  schedule:
    # Запускается каждые 3 часа (можно настроить по вашему усмотрению)
    - cron: '0 */3 * * *'
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master # Используем указанный вами форк
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # --- Опциональные параметры (см. документацию anmol098/waka-readme-stats для всех опций) ---
          SHOW_TITLE: "true" # Показать заголовок
          SHOW_LINES_OF_CODE: "true" # Показать общее количество строк кода
          SHOW_PROJECTS: "false" # Не показывать проекты
          # SHOW_PROFILE_VIEWS: "false" # Не показывать просмотры профиля
          # SHOW_DAYS_OF_WEEK: "false" # Не показывать активность по дням недели
          # SHOW_LANGUAGE_PER_REPO: "false" # Не показывать языки для каждого репозитория
          # SHOW_LOC_CHART: "false" # Не показывать график строк кода
          # SHOW_SHORT_INFO: "false" # Не показывать краткую информацию
          # SHOW_UPDATED_DATE: "true" # Показать дату последнего обновления
          LANG_COUNT: "5" # Показать топ 5 языков
          LOCALE: "en" # Язык статистики (например, "en", "ru", "ja")
          COMMIT_MESSAGE: "📊 Updated WakaTime stats" # Сообщение коммита
          # More options available, check the repository: https://github.com/anmol098/waka-readme-stats
