name: Waka Readme Stats Updater

on:
  schedule:
    # runs at 7 PM UTC (12 AM Almaty time)
    - cron: '0 19 * * *'
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
            # this action name
            - uses: athul/waka-readme@master # do NOT replace with anything else
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
                  GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  ### meta
                  API_BASE_URL: https://wakatime.com/api # optional
                  ### content
                  SHOW_TITLE: true # optional
                  SECTION_NAME: waka # optional
                  #   BLOCKS: -> # optional
                  CODE_LANG: abap # optional
                  TIME_RANGE: last_30_days # optional
                  LANG_COUNT: 5 # optional
                  SHOW_TIME: true # optional
                  SHOW_TOTAL: true # optional
                  SHOW_MASKED_TIME: false # optional
                  IGNORED_LANGUAGES: YAML JSON TOML # optional
                  ### commit
                  COMMIT_MESSAGE: updated coding metrics # optional
                  TARGET_BRANCH: main # optional
                  TARGET_PATH: README.md # optional
